["conv2d0_pre_relu", "conv2d1_pre_relu", "conv2d2_pre_relu", "head0_bottleneck_pre_relu", "head1_bottleneck_pre_relu", "mixed3a_1x1_pre_relu", "mixed3a_3x3_bottleneck_pre_relu", "mixed3a_3x3_pre_relu", "mixed3a_5x5_bottleneck_pre_relu", "mixed3a_5x5_pre_relu", "mixed3a_pool_reduce_pre_relu",
"mixed3b_1x1_pre_relu", "mixed3b_3x3_bottleneck_pre_relu", "mixed3b_3x3_pre_relu",
"mixed3b_5x5_bottleneck_pre_relu", "mixed3b_5x5_pre_relu", "mixed3b_pool_reduce_pre_relu",
"mixed4a_1x1_pre_relu", "mixed4a_3x3_bottleneck_pre_relu", "mixed4a_3x3_pre_relu",
"mixed4a_5x5_bottleneck_pre_relu", "mixed4a_5x5_pre_relu", "mixed4a_pool_reduce_pre_relu",
"mixed4b_1x1_pre_relu", "mixed4b_3x3_bottleneck_pre_relu", "mixed4b_3x3_pre_relu",
"mixed4b_5x5_bottleneck_pre_relu", "mixed4b_5x5_pre_relu", "mixed4b_pool_reduce_pre_relu",
"mixed4c_1x1_pre_relu", "mixed4c_3x3_bottleneck_pre_relu", "mixed4c_3x3_pre_relu",
"mixed4c_5x5_bottleneck_pre_relu", "mixed4c_5x5_pre_relu", "mixed4c_pool_reduce_pre_relu",
"mixed4d_1x1_pre_relu", "mixed4d_3x3_bottleneck_pre_relu", "mixed4d_3x3_pre_relu",
"mixed4d_5x5_bottleneck_pre_relu", "mixed4d_5x5_pre_relu", "mixed4d_pool_reduce_pre_relu",
"mixed4e_1x1_pre_relu", "mixed4e_3x3_bottleneck_pre_relu", "mixed4e_3x3_pre_relu",
"mixed4e_5x5_bottleneck_pre_relu", "mixed4e_5x5_pre_relu", "mixed4e_pool_reduce_pre_relu",
"mixed5a_1x1_pre_relu", "mixed5a_3x3_bottleneck_pre_relu", "mixed5a_3x3_pre_relu",
"mixed5a_5x5_bottleneck_pre_relu", "mixed5a_5x5_pre_relu", "mixed5a_pool_reduce_pre_relu",
"mixed5b_1x1_pre_relu", "mixed5b_3x3_bottleneck_pre_relu", "mixed5b_3x3_pre_relu",
"mixed5b_5x5_bottleneck_pre_relu", "mixed5b_5x5_pre_relu", "mixed5b_pool_reduce_pre_relu"]
